name: 'Update datasets'

on:
  push:
    branches: [ main ]
  schedule:
    # Dataset will be updated every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: Gr1N/setup-poetry@v4
    - name: Install dependencies
      run: |
        poetry install
    - name: Fetch all datasets
      run: |
        poetry run python -m japan_aqi.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit --allow-empty -m "Auto-update of AQI data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.gh }}